name: test
on:
  pull_request:
    branches:
      - '**'
  workflow_call:
    inputs:
      check-service-test:
        required: false
        default: false
        type: boolean

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"

    - name: Check out code into the Go module directory
      uses: actions/checkout@4

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test code
      run: make all
