name: test
on:
  pull_request:
    branches:
      - '**'
  workflow_call:
    inputs:
      check-service-test:
        required: false
        default: false
        type: boolean

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: make all
